skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_program = "2vfnmCqDAS99CnSrfRKuRTjSim2BP3fVXcG7L6AA41WC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
